Update index.md de présentation
Nuclear-Squid/ergol pull request #160
Opened 2024-03-21 15:58 UTC by Loevenbruck

- Petites corrections de texte
- Question : il faudrait uniformiser le genre des dispositions. Dvorak est considérée comme un féminin à un moment dans le texte et ça me semble pertiinent (c’est une disposition). Je serais favorable à l’idée d’uniformiser en passant toutes les dispos au féminin. Genre « Ergo-L est vraiment très jolie ».

2024-03-21 20:19 UTC, fabi1cazenave requested changes
Merci ! J’essaye d’apprendre le bon usage des ponctuations et du rythme au passage (y’a du boulot). J’ai repéré une petite erreur, je te laisse valider ma suggestion ?

2024-03-21 20:19 UTC, fabi1cazenave commented on www/content/presentation/index.md
> +variantes la reprennent sans chercher à la mettre à jour.
oups, de fait

2024-03-21 20:19 UTC, fabi1cazenave commented on www/content/presentation/index.md
> +: Taux de digrammes de même doigt en français et anglais, extrait de la [page de comparaison avec Bépo](bepo).
Il y a eu débat pour celui-ci. Tu me donnes raison. Étant très attaché à l’objectivité totale en toute circonstance, j’aime qu’on me donne raison ! :sweat_smile:

2024-03-21 20:19 UTC, fabi1cazenave commented on www/content/presentation/index.md
> +caractères accentués, diacritiques et les ponctuations spéciales. Actionner cette
Ah, intéressant. Pour moi, un seul article ça passe à l’écrit : 

> pour tous les caractères accentués, diacritiques et ponctuations spéciales

Trois articles ça passe à l’écrit comme à l’oral : 

> pour tous les caractères accentués, (tous) les diacritiques et (toutes) les ponctuations spéciales

Mais deux sur trois, j’avoue que ça me semble curieux : 

> pour tous les caractères accentués, diacritiques et les ponctuations spéciales

Je me fie bien évidemment à ton avis sur le sujet, je voulais juste m’assurer que c’est bien ça que tu voulais écrire et que tu n’as pas oublié un article en amendant le texte ?

2024-03-21 20:19 UTC, fabi1cazenave commented on www/content/presentation/index.md
> +Comme pour l’emplacement des lettres de la disposition, une grande attention a
:facepalm:

2024-03-21 20:19 UTC, fabi1cazenave commented on www/content/presentation/index.md
>  - les symboles arithmétiques `+` `-` `/` `*`
Avec cette modification on obtient ça : 

![image](https://github.com/Nuclear-Squid/ergol/assets/457778/c45a0cfa-48d0-45e1-80b0-58f42ee0c4f2)

Je crois que tu as mal placé un point-virgule, et que ce que tu voulais écrire c’est ça : 
```suggestion
- les délimiteurs `()` `{}` `[]` `<>` ;
- les délimiteurs de chaîne de caractères ``'`"` ;
- les symboles arithmétiques `+` `-` `/` `*` ;
```

2024-03-21 21:26 UTC, Loevenbruck commented on www/content/presentation/index.md
> +: Taux de digrammes de même doigt en français et anglais, extrait de la [page de comparaison avec Bépo](bepo).
À la limite « mêmes doigts » ça passerait, mais « même doigts »... vous allez avoir du mal à faire passer ce « même » pour un adverbe, devant le juge.

2024-03-21 21:31 UTC, Loevenbruck commented on www/content/presentation/index.md
> +caractères accentués, diacritiques et les ponctuations spéciales. Actionner cette
Ah, oui, là c’est mon inculture dactylographique qui a joué : j’ai cru que diacritique se rapportait aussi à caractères.  
Si ce n’est pas le cas alors ça passe.

2024-03-21 21:34 UTC, Loevenbruck commented on www/content/presentation/index.md
>  - les symboles arithmétiques `+` `-` `/` `*`
Euh... Je suis paumé, là :-) Je voulais un point virgule aux premiers éléments de la liste, et un point au dernier.

2024-03-21 21:42 UTC, Loevenbruck commented on www/content/presentation/index.md
> +caractères accentués, diacritiques et les ponctuations spéciales. Actionner cette
Dis-moi si diacritiques est ou non un adjectif se rapportant à caractères. Si ce n’est pas le cas je vire en effet ma correction.

2024-03-22 16:54 UTC, Loevenbruck commented on www/content/presentation/index.md
>  - les symboles arithmétiques `+` `-` `/` `*`
Là je pense que c’est bon.

2024-03-30 11:52 UTC, Nuclear-Squid requested changes

2024-03-30 11:52 UTC, Nuclear-Squid commented on www/content/presentation/index.md
> +- les délimiteurs de chaîne de caractères `'` `"` ;
Avec ce changement tu mets le `'` et `"` dans des blocs à part (ce qui est ce qu’on veut), mais on pert aussi le `` ` `` (backtick), qui est aussi un délimiteur de chaîne dans certains langages (comme markdown pour les blocs de code, dans notre cas).

Pour mettre le backtick dans un bloc de code c’est un peu bizarre mais tu peux faire comme ça :

```
`` ` ``  (bt bt espace bt espace bt bt; bt = backtick)
```

Tous les délimiteurs de chaîne ensemble donne donc :

```
`'` `` ` `` `"`
```

(Tu peux copier-coller le deuxième bloc que je t’ai donné, y’a même les joli espaces insécables fines ^^)

2024-05-19 11:08 UTC, merged