Harmonisation de détails, suite
Nuclear-Squid/ergol pull request #217
Opened 2024-07-29 10:45 UTC by aurelberra

2024-07-31 11:17 UTC, fabi1cazenave requested changes
Top ! J’ai émis quelques maniaqueries et quelques questions mais j’apprécie vivement le boulot que tu fais, merci !

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/alternatives/_index.md
> +la rangée inférieure) et trop de digrammes courants sont trop inconfortables
On pourrait en profiter pour éviter la répétition sur « trop » ? e.g. « beaucoup de digrammes courants sont trop inconfortables » ?

(Ouais j’ai utilisé un « e.g. », ch’uis un ouf, kestuvafère ?!? :-))

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/articles/apprendre_a_taper/index.md
> +s’apprendre sur le tas –, mais certain·e·s restent jusqu’au bout, souvent pour
virgule après le tiret de césure ?

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/articles/apprendre_a_taper/index.md
> +recommande d’aller vous entraîner sur [Monkeytype][]. Ce site
Oups !!!

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/articles/apprendre_a_taper/index.md
> +40 WPM au dessus pour les digrammes.
pourquoi les majuscules à `wpm` ? Ce n’est certes pas une unité SI mais il me semble que les unités en majuscules sont très rares. Et puisqu’ici on utilise une abréviation anglophone, `wpm` me semble plus proche de `mph` ou `kph` qui sont courantes.

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
Pour les énumérations il me semblait pourtant que l’approche initiale était correcte.
En tout cas je suis surpris de commencer la première ligne par une majuscule alors que la proposition d’avant se termine par `:`.  Si tu as un lien pour expliquer la règle je suis preneur.

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/claviers/arsenik/index.md
> +[Kanata][] est un logiciel libre et multiplateforme permettant de redéfinir le
Hmm, là je suis quasi certain que la première formulation est la bonne. Ça fait partie des tous premiers trucs qu’on m’a demandé d’adopter lors de mon tout premier contrat de travail, il y a fort longtemps.

https://fr.wikipedia.org/wiki/Plate-forme_(informatique)

2024-07-31 11:17 UTC, fabi1cazenave commented on www/content/claviers/arsenik/index.md
> +3. <i lang="en">Homerow-mods</i>
pareil, puisque la proposition précédente se termine par `:` je suis surpris de démarrer les items de liste par une majuscule…

2024-07-31 11:43 UTC, fabi1cazenave commented
Suite à la fusion d’une autre PR j’ai dû résoudre des conflits manuellement. Pense à `git pull` !

2024-07-31 20:52 UTC, aurelberra commented on www/content/claviers/arsenik/index.md
> +[Kanata][] est un logiciel libre et multiplateforme permettant de redéfinir le
La graphie initiale semble tout à fait correcte, comme les deux autres variantes (https://fr.m.wiktionary.org/wiki/multiplateforme) – en supprimant le S final au singulier, bien sûr. Je proposais la forme des rectifications de 1990, qui soude le préfixe, et je suivais mon habitude d'écrire « plateforme » en un seul mot. Ce qui me choquait un peu, d'un point de vue logique, c'était de souder le préfixe mais de garder un mot composé. Tu as le dernier mot : il faut surtout se rappeler d'harmoniser la pratique sur le site, si possible !

2024-08-01 06:34 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
La typo des listes n'est pas entièrement claire, surtout parce que l'abus des parenthèses en tête d'éléments de liste est endémique et parce que la règle des deux-points en fin d'élément tombe en désuétude. Mon repère est qu'un point est suivi d'une majuscule. Voici comment le dit Lacroux :

> Les signes « avec point » :
A. B.I. II.1. 2.
Les signes « sans point » :
1o 2oa) b)— (tiret… formule la plus fréquente).
Avec les premiers, on a une majuscule initiale au premier mot et un point final pour chaque élément de l’énumération. Avec les seconds, on a une minuscule initiale au premier mot et un point-virgule pour chaque élément de l’énumération (sauf le dernier, qui, dans les cas où l’énumération clôt la phrase, est un point final). (<https://www.orthotypographie.fr/volume-I/echelle-extrait.html>, sous « Énumération »)

2024-08-01 06:38 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
Quant à l'introduction par le deux-points, ça ne me choque pas (moins maintenant, mais on introduisait parfois de cette façon même un paragraphe). C'est souvent plus simple et propre de choisir entre deux types de listes : avec point à la phrase d'introduction et 1. 2. 3. aux éléments ; avec deux-points pour introduire et tirets, puces ou a) b) c) aux éléments.

2024-08-01 06:40 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
Je dirais donc que l'état initial des listes sur le site mélange deux styles et qu'il vaut mieux choisir. C'est mon avis, rien de plus, mais je le partage.

2024-08-01 06:41 UTC, aurelberra commented on www/content/claviers/arsenik/index.md
> +3. <i lang="en">Homerow-mods</i>
Comme plus haut, à voir !

2024-08-01 07:01 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +40 WPM au dessus pour les digrammes.
Ce n'est pas évident, et la cohérence prime, comme toujours. Je ne m'étais jamais demandé ce qu'il en était des unités courantes mais non standard (en fait, on peut en inventer autant qu'on veut : digrammes du même doigt par minute par personne et par continent…). Je les traitais spontanément comme des abréviations, à partir du moment où nous n'avons pas des normes (SI et conventions pour les unités bien partagées). Pour les kilomètres par heure, le français écrit logiquement « km/h ». L'anglais hésite un peu. Les ressources auxquelles je peux accéder à l'instant varient et ne sont pas cohérentes pour nos mots par minute. Si je devais trancher, j'harmoniserais vers les capitales qui signalent une abréviation. Cela permet aussi de ne pas écrire en anglais « wpm » et en français « mots/min ». Si tu tiens à « wpm » et « mpm » comme termes techniques, ce n'est pas un crime…  En tout cas, une note dans le glossaire est bienvenue.

2024-08-01 07:04 UTC, aurelberra commented on www/content/alternatives/_index.md
> +la rangée inférieure) et trop de digrammes courants sont trop inconfortables
Excellente idée. Le correcteur n'est pas un professeur de style ni de vertu, mais j'approuve :-)

2024-08-01 07:15 UTC, aurelberra commented on www/content/alternatives/_index.md
> +La contrepartie, c’est la [touche morte][] qu’il faut apprendre, et qui ajoute
Je n'ai pas de religion, ni le Drillon sous la main (<https://www.gallimard.fr/Catalogue/GALLIMARD/Tel/Traite-de-la-ponctuation-francaise>). J'ai remarqué cette habitude sur le site. C'est sans doute largement une question de goût. Ici, j'ai peut-être inutilement sévi ! Il me semble assez logique de mettre une virgule : « La contrepartie est l'amélioration des… » est la syntaxe neutre ; « La contrepartie, c'est l'amélioration des… » est une syntaxe clivée, à priori pour créer un effet d'insistance. Je pense que peu de gens se poseront la question dans notre contexte et il n'y a aucune ambiguïté : tout est possible !

2024-08-01 07:23 UTC, aurelberra commented on www/content/alternatives/_index.md
> +entre 2,5 % et 4,0 % de frappes supplémentaires en français — soit une perte de 2 mots/minute pour une personne tapant à 60 mots/minute.
Désolé ! J'avais fait certaines de ces corrections sur ma machine avant notre autre discussion. Ici, peux-tu rectifier ? Tout n'est pas facile sur l'écran du téléphone où je te réponds – c'est jour de voyage pour moi.

2024-08-01 07:28 UTC, aurelberra commented
Merci pour tes remarques. Être contraint de réfléchir, c'est toujours une bonne chose !

Vraiment désolé pour le cafouillage des commits. J'ai regardé parfois sur mon téléphone et parfois sur un ordinateur, en vadrouille, et j'ai visiblement eu un problème, que je n'ai pas voulu aggraver, alors que j'avais cru faire comme d'habitude…

2024-08-01 21:31 UTC, aurelberra commented
J’ai corrigé les détails pour lesquels la discussion était close.

2024-08-04 18:45 UTC, fabi1cazenave commented on www/content/articles/apprendre_a_taper/index.md
> +40 WPM au dessus pour les digrammes.
Je serais partant pour `wpm` en tant qu’unité, oui.

Effectivement il faudrait ajouter ça au glossaire (en mentionnant le fait que 1 wpm == 5 cpm) et faire un fichier `CONTRIBUTING.md` à la racine du site web contenant les conventions typographiques.

2024-08-04 18:48 UTC, fabi1cazenave commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
Perso je crois qu’une énumération gagne à être courte, et donc se limiter à une seule phrase — donc à une suite de propositions séparées par des point-virgule. Mais si tu as un avis fort dans l’autre sens on le suivra.

2024-08-04 18:49 UTC, fabi1cazenave commented on www/content/claviers/arsenik/index.md
> +[Kanata][] est un logiciel libre et multiplateforme permettant de redéfinir le
Alors va pour multiplate-forme (j’avais même pas vu la faute d’accord), qu’on m’avait « vendu » comme la graphie correcte mais dont j’ai oublié la raison. À ajouter au `CONTRIBUTING.md` un jour.

2024-08-04 18:50 UTC, fabi1cazenave commented on www/content/claviers/arsenik/index.md
> +3. <i lang="en">Homerow-mods</i>
Alors pareil. Je suis plutôt sur l’approche « une énumération == une seule phrase » mais on suivra ton avis.

2024-08-04 20:15 UTC, fabi1cazenave reviewed
Quelques notes à propos de l’article sur Vim. :-)

2024-08-04 20:15 UTC, fabi1cazenave commented on www/content/articles/vim_pour_les_ergonautes/index.md
> +À une époque fort lointaine, où j’aimais déjà Vim mais contribuais au
C’était une allusion à Shrek mais effectivement, ça risque de passer pour une typo.

2024-08-04 20:15 UTC, fabi1cazenave commented on www/content/articles/vim_pour_les_ergonautes/index.md
> +> avec mes mappings Bépo hasardeux–.
Pourquoi le tiret en fin de ligne ?

2024-08-04 20:15 UTC, fabi1cazenave commented on www/content/articles/vim_pour_les_ergonautes/index.md
> +structures de ce genre permet de s’économiser encore des actions dans Vim.
Le terme « structures » est ici inexact. Peut-être peut-on reformuler de la sorte : 

> Ce dernier `ciw` utilise un text object. Maitriser ce type d’opérations permet d’économiser encore des actions dans Vim.

2024-08-04 20:15 UTC, fabi1cazenave commented on www/content/articles/vim_pour_les_ergonautes/index.md
>  gauche, donc je n’ai pas l’impression de perdre en confort.
Je crois avoir déjà reformulé cette partie-là, à rebaser donc.

2024-08-04 21:05 UTC, aurelberra commented on www/content/articles/vim_pour_les_ergonautes/index.md
> +À une époque fort lointaine, où j’aimais déjà Vim mais contribuais au
Ah ! Je connais mal Shrek en anglais et pas du tout en français… Sinon, j'aurais écrit « fort, fort lointaine ». Mieux pour toi ?

2024-08-04 21:06 UTC, aurelberra commented on www/content/articles/vim_pour_les_ergonautes/index.md
> +structures de ce genre permet de s’économiser encore des actions dans Vim.
Parfait ! On avait un problème entre le singulier et le pluriel.

2024-08-05 08:50 UTC, fabi1cazenave commented
J’ai poussé des commits reprenant l’essentiel de tes corrections de l’article sur Vim : https://github.com/Nuclear-Squid/ergol/pull/222/files

Je vais voir si je peux rebaser d’ici ce soir.

2024-08-05 09:36 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +40 WPM au dessus pour les digrammes.
Adjugé !

2024-08-05 09:41 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
Ce sera très bien, et si cela suit ton habitude ce sera facile d’avoir une pratique cohérente. Dans ce cas, il faudrait ne pas utiliser une structure avec des points du type « 1. […] ; 2. […] ; 3. […]. » De préférence. Peut-être « 1) […] ; 2) […] ; 3) […]. » ? Ou simplement des tirets ?

2024-08-05 09:43 UTC, aurelberra commented on www/content/articles/apprendre_a_taper/index.md
> +4. On rajoute des challenges plus compliqués :
Je me demande si les programmeurs n’ont pas une plus grande tolérance, voire un attachement au point-virgule en fin de phrase ;-)

2024-08-05 09:43 UTC, aurelberra commented on www/content/claviers/arsenik/index.md
> +[Kanata][] est un logiciel libre et multiplateforme permettant de redéfinir le
C’est parti.

2024-08-06 10:27 UTC, fabi1cazenave approved these changes
Il reste une paire de WPM en majuscules et je ne suis toujours pas convaincu par les énumérations sans points-virgules, mais on va laisser une pause aux drosophiles pour le moment. Merci pour le boulot !

2024-08-06 10:27 UTC, merged